apiVersion: metallb.io/v1beta1
kind: MetalLB
metadata:
  name: metallb
  namespace: metallb-system
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""


# https://docs.openshift.com/container-platform/4.14/networking/metallb/metallb-operator-install.html
# oc get MetalLB/<MetalLB_name> -n metallb-system -o yaml